// Generated by delombok at Mon Aug 03 06:24:16 IST 2026
package com.medistock.medistockbackend.controller;

import com.medistock.medistockbackend.entity.Medicine;
import com.medistock.medistockbackend.service.MedicineService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/medicines")
public class MedicineController {
    private final MedicineService service;

    @GetMapping
    public ResponseEntity<List<Medicine>> getAll() {
        return ResponseEntity.ok(service.findAll());
    }

    @GetMapping("/{id}")
    public ResponseEntity<Medicine> getById(@PathVariable Long id) {
        return ResponseEntity.ok(service.findById(id));
    }

    @PostMapping
    public ResponseEntity<Medicine> create(@RequestBody com.medistock.medistockbackend.dto.MedicineRequestDto dto) {
        Medicine entity = new Medicine();
        entity.setName(dto.getName());
        entity.setDescription(dto.getDescription());
        entity.setCategory(dto.getCategory());
        entity.setPrice(dto.getPrice());
        if (dto.getSupplier() != null) {
            com.medistock.medistockbackend.entity.Supplier supplier = new com.medistock.medistockbackend.entity.Supplier();
            supplier.setId(dto.getSupplier().getId());
            entity.setSupplier(supplier);
        } else {
            entity.setSupplier(null);
        }
        return ResponseEntity.ok(service.save(entity));
    }

    @PutMapping("/{id}")
    public ResponseEntity<Medicine> update(@PathVariable Long id, @RequestBody com.medistock.medistockbackend.dto.MedicineRequestDto dto) {
        Medicine entity = service.findById(id);
        entity.setName(dto.getName());
        entity.setDescription(dto.getDescription());
        entity.setCategory(dto.getCategory());
        entity.setPrice(dto.getPrice());
        if (dto.getSupplier() != null) {
            com.medistock.medistockbackend.entity.Supplier supplier = new com.medistock.medistockbackend.entity.Supplier();
            supplier.setId(dto.getSupplier().getId());
            entity.setSupplier(supplier);
        } else {
            entity.setSupplier(null);
        }
        return ResponseEntity.ok(service.save(entity));
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        service.deleteById(id);
        return ResponseEntity.ok().build();
    }

    @GetMapping("/search")
    public ResponseEntity<List<Medicine>> searchByName(@RequestParam String name) {
        return ResponseEntity.ok(service.searchByName(name));
    }

    @GetMapping("/filter/category")
    public ResponseEntity<List<Medicine>> filterByCategory(@RequestParam String category) {
        return ResponseEntity.ok(service.findByCategory(category));
    }

    @GetMapping("/filter/supplier")
    public ResponseEntity<List<Medicine>> filterBySupplier(@RequestParam Long supplierId) {
        return ResponseEntity.ok(service.findBySupplier(supplierId));
    }

    @GetMapping("/filter/stock")
    public ResponseEntity<List<Medicine>> filterByStockStatus(@RequestParam String status) {
        return ResponseEntity.ok(service.filterByStockStatus(status));
    }

    @java.lang.SuppressWarnings("all")
    public MedicineController(final MedicineService service) {
        this.service = service;
    }
}
