// Generated by delombok at Mon Aug 03 06:24:16 IST 2026
package com.medistock.medistockbackend.controller;

import com.medistock.medistockbackend.entity.PurchaseOrder;
import com.medistock.medistockbackend.service.PurchaseOrderService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

import com.medistock.medistockbackend.entity.Notification;
import com.medistock.medistockbackend.entity.User;
import com.medistock.medistockbackend.repository.NotificationRepository;
import com.medistock.medistockbackend.repository.UserRepository;

@RestController
@RequestMapping("/api/purchaseorders")
public class PurchaseOrderController {
    private final PurchaseOrderService service;
    private final NotificationRepository notificationRepository;
    private final UserRepository userRepository;

    public PurchaseOrderController(final PurchaseOrderService service,
                                   final NotificationRepository notificationRepository,
                                   final UserRepository userRepository) {
        this.service = service;
        this.notificationRepository = notificationRepository;
        this.userRepository = userRepository;
    }

    @GetMapping
    public ResponseEntity<List<PurchaseOrder>> getAll() {
        return ResponseEntity.ok(service.findAll());
    }

    @GetMapping("/{id}")
    public ResponseEntity<PurchaseOrder> getById(@PathVariable Long id) {
        return ResponseEntity.ok(service.findById(id));
    }

    @PostMapping
    public ResponseEntity<PurchaseOrder> create(@RequestBody PurchaseOrder entity) {
        return ResponseEntity.ok(service.save(entity));
    }

    @PutMapping("/{id}")
    public ResponseEntity<PurchaseOrder> update(@PathVariable Long id, @RequestBody PurchaseOrder entity) {
        entity.setId(id);
        return ResponseEntity.ok(service.save(entity));
    }

    @PostMapping("/{id}/submit-bill")
    public ResponseEntity<PurchaseOrder> submitBill(@PathVariable Long id, @RequestBody(required = false) java.util.Map<String, Object> payload) {
        PurchaseOrder po = service.findById(id);
        po.setStatus("BILL_SUBMITTED");
        PurchaseOrder savedPo = service.save(po);

        try {
            double amount = 0.0;
            if (payload != null && payload.get("amount") != null) {
                amount = Double.parseDouble(payload.get("amount").toString());
            }
            String supplierName = savedPo.getSupplier() != null ? savedPo.getSupplier().getName() : "Supplier";

            User adminUser = userRepository.findAll().stream()
                    .filter(u -> u.getRole() != null &&
                            ("ROLE_ADMIN".equalsIgnoreCase(u.getRole().getName()) ||
                             "ADMIN".equalsIgnoreCase(u.getRole().getName())))
                    .findFirst()
                    .orElseGet(() -> userRepository.findAll().stream().findFirst().orElse(null));

            if (adminUser != null) {
                Notification n = new Notification();
                n.setUser(adminUser);
                n.setTitle("Bill Submitted");
                n.setType("BILL_SUBMITTED");
                n.setMessage("Bill submitted by " + supplierName + " for Stock Order #PO-" + id + ". Amount: ₹" + (int)amount + ". Please review the bill.");
                n.setIsRead(false);
                n.setTimestamp(java.time.LocalDateTime.now());
                notificationRepository.save(n);
            }
        } catch (Exception e) {
            // Non-blocking notification creation
        }

        return ResponseEntity.ok(savedPo);
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        service.deleteById(id);
        return ResponseEntity.ok().build();
    }
}
