// Generated by delombok at Mon Aug 03 06:19:19 IST 2026
package com.medistock.medistockbackend.controller;

import com.medistock.medistockbackend.entity.StockLog;
import com.medistock.medistockbackend.service.StockLogService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/stocklogs")
public class StockLogController {
    private final StockLogService service;

    @GetMapping
    public ResponseEntity<List<StockLog>> getAll() {
        return ResponseEntity.ok(service.findAll());
    }

    @GetMapping("/{id}")
    public ResponseEntity<StockLog> getById(@PathVariable Long id) {
        return ResponseEntity.ok(service.findById(id));
    }

    @PostMapping
    public ResponseEntity<StockLog> create(@RequestBody StockLog entity) {
        return ResponseEntity.ok(service.save(entity));
    }

    @PutMapping("/{id}")
    public ResponseEntity<StockLog> update(@PathVariable Long id, @RequestBody StockLog entity) {
        entity.setId(id);
        return ResponseEntity.ok(service.save(entity));
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        service.deleteById(id);
        return ResponseEntity.ok().build();
    }

    @java.lang.SuppressWarnings("all")
    public StockLogController(final StockLogService service) {
        this.service = service;
    }
}
