// Generated by delombok at Mon Aug 03 06:24:16 IST 2026
package com.medistock.medistockbackend.service.impl;

import com.medistock.medistockbackend.entity.ExpiryTracking;
import com.medistock.medistockbackend.repository.ExpiryTrackingRepository;
import com.medistock.medistockbackend.service.ExpiryTrackingService;
import com.medistock.medistockbackend.exception.ResourceNotFoundException;
import org.springframework.stereotype.Service;
import java.util.List;

@Service
public class ExpiryTrackingServiceImpl implements ExpiryTrackingService {
    private final ExpiryTrackingRepository repository;
    private final com.medistock.medistockbackend.repository.InventoryRepository inventoryRepository;

    @Override
    public List<ExpiryTracking> findAll() {
        return repository.findAll();
    }

    @Override
    public ExpiryTracking findById(Long id) {
        return repository.findById(id).orElseThrow(() -> new ResourceNotFoundException("ExpiryTracking not found with id: " + id));
    }

    @Override
    public ExpiryTracking save(ExpiryTracking entity) {
        return repository.save(entity);
    }

    @Override
    public void deleteById(Long id) {
        repository.deleteById(id);
    }

    @Override
    public List<ExpiryTracking> getUpcomingExpirys() {
        java.time.LocalDate today = java.time.LocalDate.now();
        java.time.LocalDate threshold = today.plusYears(5);
        
        return inventoryRepository.findUpcomingExpiries(threshold).stream().map(inv -> {
            ExpiryTracking mock = new ExpiryTracking();
            mock.setId(inv.getId());
            mock.setMedicineName(inv.getMedicine() != null ? inv.getMedicine().getName() : "Unknown Medicine");
            mock.setExpiryDate(inv.getExpiryDate());
            mock.setStatus(inv.getExpiryDate().isBefore(today) ? "Expired" : "Near Expiry");
            return mock;
        }).collect(java.util.stream.Collectors.toList());
    }

    @java.lang.SuppressWarnings("all")
    public ExpiryTrackingServiceImpl(final ExpiryTrackingRepository repository, final com.medistock.medistockbackend.repository.InventoryRepository inventoryRepository) {
        this.repository = repository;
        this.inventoryRepository = inventoryRepository;
    }
}
