// Generated by delombok at Mon Aug 03 06:24:16 IST 2026
package com.medistock.medistockbackend.service.impl;

import com.medistock.medistockbackend.entity.Inventory;
import com.medistock.medistockbackend.repository.InventoryRepository;
import com.medistock.medistockbackend.service.InventoryService;
import com.medistock.medistockbackend.exception.ResourceNotFoundException;
import org.springframework.stereotype.Service;
import java.util.List;

import com.medistock.medistockbackend.entity.Medicine;
import com.medistock.medistockbackend.entity.Notification;
import com.medistock.medistockbackend.entity.User;
import com.medistock.medistockbackend.repository.MedicineRepository;
import com.medistock.medistockbackend.repository.NotificationRepository;
import com.medistock.medistockbackend.repository.UserRepository;

@Service
public class InventoryServiceImpl implements InventoryService {
    private final InventoryRepository repository;
    private final MedicineRepository medicineRepository;
    private final NotificationRepository notificationRepository;
    private final UserRepository userRepository;

    public InventoryServiceImpl(final InventoryRepository repository,
                                final MedicineRepository medicineRepository,
                                final NotificationRepository notificationRepository,
                                final UserRepository userRepository) {
        this.repository = repository;
        this.medicineRepository = medicineRepository;
        this.notificationRepository = notificationRepository;
        this.userRepository = userRepository;
    }

    private void checkLowStockForMedicine(Medicine medicine) {
        if (medicine == null || medicine.getId() == null) return;
        try {
            Medicine med = medicineRepository.findById(medicine.getId()).orElse(medicine);
            List<Inventory> invs = repository.findAll().stream()
                    .filter(i -> i.getMedicine() != null && medicine.getId().equals(i.getMedicine().getId()))
                    .toList();

            int totalQty = invs.stream().mapToInt(i -> i.getQuantity() != null ? i.getQuantity() : 0).sum();
            int minStock = invs.stream().filter(i -> i.getMinimumStock() != null).mapToInt(Inventory::getMinimumStock).max().orElse(10);

            med.setStockQuantity(totalQty);
            medicineRepository.save(med);

            if (totalQty > 0 && totalQty <= minStock) {
                String medName = med.getName();
                List<Notification> existing = notificationRepository.findAll();
                boolean exists = existing.stream().anyMatch(n ->
                    n.getMessage() != null && n.getMessage().contains(medName) &&
                    "LOW_STOCK".equalsIgnoreCase(n.getType()) &&
                    (n.getIsRead() == null || !n.getIsRead())
                );

                if (!exists) {
                    User adminUser = userRepository.findAll().stream()
                            .filter(u -> u.getRole() != null &&
                                    ("ROLE_ADMIN".equalsIgnoreCase(u.getRole().getName()) ||
                                     "ADMIN".equalsIgnoreCase(u.getRole().getName())))
                            .findFirst()
                            .orElseGet(() -> userRepository.findAll().stream().findFirst().orElse(null));

                    if (adminUser != null) {
                        Notification n = new Notification();
                        n.setUser(adminUser);
                        n.setTitle("Low Stock Alert");
                        n.setType("LOW_STOCK");
                        n.setMessage("Low Stock Alert: " + medName + " stock is below the minimum level. Current quantity: " + totalQty + ".");
                        n.setIsRead(false);
                        n.setTimestamp(java.time.LocalDateTime.now());
                        notificationRepository.save(n);
                    }
                }
            }
        } catch (Exception e) {
            // Non-blocking
        }
    }

    @Override
    public List<Inventory> findAll() {
        return repository.findAll();
    }

    @Override
    public Inventory findById(Long id) {
        return repository.findById(id).orElseThrow(() -> new ResourceNotFoundException("Inventory not found with id: " + id));
    }

    @Override
    public Inventory save(Inventory entity) {
        Inventory saved = repository.save(entity);
        if (saved.getMedicine() != null) {
            checkLowStockForMedicine(saved.getMedicine());
        }
        return saved;
    }

    @Override
    public void deleteById(Long id) {
        repository.deleteById(id);
    }

    @Override
    public Inventory updateStock(Long id, Integer quantity) {
        Inventory inventory = findById(id);
        inventory.setQuantity(quantity);
        Inventory saved = repository.save(inventory);
        if (saved.getMedicine() != null) {
            checkLowStockForMedicine(saved.getMedicine());
        }
        return saved;
    }
}
