// Generated by delombok at Mon Aug 03 06:24:16 IST 2026
package com.medistock.medistockbackend.service.impl;

import com.medistock.medistockbackend.entity.Inventory;
import com.medistock.medistockbackend.repository.InventoryRepository;
import com.medistock.medistockbackend.service.InventoryService;
import com.medistock.medistockbackend.exception.ResourceNotFoundException;
import org.springframework.stereotype.Service;
import java.util.List;

@Service
public class InventoryServiceImpl implements InventoryService {
    private final InventoryRepository repository;

    @Override
    public List<Inventory> findAll() {
        return repository.findAll();
    }

    @Override
    public Inventory findById(Long id) {
        return repository.findById(id).orElseThrow(() -> new ResourceNotFoundException("Inventory not found with id: " + id));
    }

    @Override
    public Inventory save(Inventory entity) {
        return repository.save(entity);
    }

    @Override
    public void deleteById(Long id) {
        repository.deleteById(id);
    }

    @Override
    public Inventory updateStock(Long id, Integer quantity) {
        Inventory inventory = findById(id);
        inventory.setQuantity(quantity);
        return repository.save(inventory);
    }

    @java.lang.SuppressWarnings("all")
    public InventoryServiceImpl(final InventoryRepository repository) {
        this.repository = repository;
    }
}
