// Generated by delombok at Mon Aug 03 06:24:16 IST 2026
package com.medistock.medistockbackend.service.impl;

import com.medistock.medistockbackend.entity.Medicine;
import com.medistock.medistockbackend.repository.MedicineRepository;
import com.medistock.medistockbackend.service.MedicineService;
import com.medistock.medistockbackend.exception.ResourceNotFoundException;
import org.springframework.stereotype.Service;
import java.util.List;

@Service
public class MedicineServiceImpl implements MedicineService {
    private final MedicineRepository repository;

    @Override
    public List<Medicine> findAll() {
        return repository.findAll();
    }

    @Override
    public Medicine findById(Long id) {
        return repository.findById(id).orElseThrow(() -> new ResourceNotFoundException("Medicine not found with id: " + id));
    }

    @Override
    public Medicine save(Medicine entity) {
        return repository.save(entity);
    }

    @Override
    public void deleteById(Long id) {
        repository.deleteById(id);
    }

    @Override
    public List<Medicine> searchByName(String name) {
        return repository.findByNameContainingIgnoreCase(name);
    }

    @Override
    public List<Medicine> findByCategory(String category) {
        return repository.findByCategoryIgnoreCase(category);
    }

    @Override
    public List<Medicine> findBySupplier(Long supplierId) {
        return repository.findBySupplierId(supplierId);
    }

    @Override
    public List<Medicine> filterByStockStatus(String status) {
        if ("available".equalsIgnoreCase(status)) {
            return repository.findAvailableMedicines();
        } else if ("low".equalsIgnoreCase(status) || "low stock".equalsIgnoreCase(status)) {
            return repository.findLowStockMedicines();
        }
        // If unknown status, return empty list or all, let's just return all for fallback or maybe empty
        return java.util.Collections.emptyList();
    }

    @java.lang.SuppressWarnings("all")
    public MedicineServiceImpl(final MedicineRepository repository) {
        this.repository = repository;
    }
}
