// Generated by delombok at Mon Aug 03 06:24:16 IST 2026
package com.medistock.medistockbackend.service.impl;

import com.medistock.medistockbackend.entity.Notification;
import com.medistock.medistockbackend.repository.NotificationRepository;
import com.medistock.medistockbackend.service.NotificationService;
import com.medistock.medistockbackend.exception.ResourceNotFoundException;
import org.springframework.stereotype.Service;
import java.util.List;

@Service
public class NotificationServiceImpl implements NotificationService {
    private final NotificationRepository repository;

    @Override
    public List<Notification> findAll() {
        return repository.findAll();
    }

    @Override
    public Notification findById(Long id) {
        return repository.findById(id).orElseThrow(() -> new ResourceNotFoundException("Notification not found with id: " + id));
    }

    @Override
    public Notification save(Notification entity) {
        return repository.save(entity);
    }

    @Override
    public void deleteById(Long id) {
        repository.deleteById(id);
    }

    @Override
    public Notification markAsRead(Long id) {
        Notification notification = findById(id);
        notification.setIsRead(true);
        return repository.save(notification);
    }

    @java.lang.SuppressWarnings("all")
    public NotificationServiceImpl(final NotificationRepository repository) {
        this.repository = repository;
    }
}
