// Generated by delombok at Mon Aug 03 06:24:16 IST 2026
package com.medistock.medistockbackend.service.impl;

import com.medistock.medistockbackend.entity.StockLog;
import com.medistock.medistockbackend.repository.StockLogRepository;
import com.medistock.medistockbackend.service.StockLogService;
import com.medistock.medistockbackend.exception.ResourceNotFoundException;
import org.springframework.stereotype.Service;
import java.util.List;

@Service
public class StockLogServiceImpl implements StockLogService {
    private final StockLogRepository repository;

    @Override
    public List<StockLog> findAll() {
        return repository.findAll();
    }

    @Override
    public StockLog findById(Long id) {
        return repository.findById(id).orElseThrow(() -> new ResourceNotFoundException("StockLog not found with id: " + id));
    }

    @Override
    public StockLog save(StockLog entity) {
        return repository.save(entity);
    }

    @Override
    public void deleteById(Long id) {
        repository.deleteById(id);
    }

    @java.lang.SuppressWarnings("all")
    public StockLogServiceImpl(final StockLogRepository repository) {
        this.repository = repository;
    }
}
