spring.application.name=medistock-backend

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/medistock
spring.datasource.username=root
spring.datasource.password=Sakshi@25

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080