import { Medicine, Category, StockLog } from '../types/inventory';
import { Supplier } from '../types/supplier';
import { PurchaseOrder } from '../types/order';
import { NotificationItem } from '../types/notification';
import { User } from '../types/user';

export const MOCK_USER: User = {
  id: 'usr_001',
  name: 'Dr. Sarah Jenkins',
  email: 'sarah.jenkins@medistock.health',
  role: 'Chief Pharmacist',
  avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
  department: 'Central Hospital Pharmacy',
  status: 'Active',
  lastActive: 'Just now',
  phone: '+1 (555) 234-5678',
};

export const MOCK_USERS: User[] = [
  MOCK_USER,
  {
    id: 'usr_002',
    name: 'Marcus Vance',
    email: 'marcus.vance@medistock.health',
    role: 'Admin',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    department: 'IT & System Admin',
    status: 'Active',
    lastActive: '5 mins ago',
    phone: '+1 (555) 890-1234',
  },
  {
    id: 'usr_003',
    name: 'Elena Rostova',
    email: 'elena.r@medistock.health',
    role: 'Supplier',
    avatar: 'https://images.unsplash.com/photo-1594824813566-88855ce78907?w=150&auto=format&fit=crop&q=80',
    department: 'Logistics & Supply Chain',
    status: 'Active',
    lastActive: '1 hour ago',
    phone: '+1 (555) 456-7890',
  },
  {
    id: 'usr_004',
    name: 'David Chen',
    email: 'david.chen@medistock.health',
    role: 'Staff Pharmacist',
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80',
    department: 'Outpatient Dispensing',
    status: 'Active',
    lastActive: '3 hours ago',
    phone: '+1 (555) 789-0123',
  },
  {
    id: 'usr_005',
    name: 'Amara Okafor',
    email: 'amara.okafor@medistock.health',
    role: 'Staff Pharmacist',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Emergency Care Unit',
    status: 'Pending',
    lastActive: 'Yesterday',
    phone: '+1 (555) 321-6547',
  },
];

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat_1', name: 'Analgesic / Antipyretic', itemCount: 450, description: 'Fever reducers and mild to moderate pain relievers', iconName: 'Activity' },
  { id: 'cat_2', name: 'Antibiotic', itemCount: 320, description: 'Antibacterial formulations for systemic & topical infections', iconName: 'Pill' },
  { id: 'cat_3', name: 'Antihistamine', itemCount: 180, description: 'Allergy relief and anti-inflammatory histaminic blockers', iconName: 'Wind' },
  { id: 'cat_4', name: 'Gastrointestinal', itemCount: 290, description: 'Acid reflux, proton pump inhibitors, and antiemetic agents', iconName: 'Activity' },
  { id: 'cat_5', name: 'NSAID / Pain Relief', itemCount: 310, description: 'Nonsteroidal anti-inflammatory drugs and joint care', iconName: 'Activity' },
  { id: 'cat_6', name: 'Antidiabetic', itemCount: 240, description: 'Oral hypoglycemics and glycemic regulators', iconName: 'Dna' },
  { id: 'cat_7', name: 'Antihypertensive', itemCount: 210, description: 'Blood pressure control and cardiovascular therapy', iconName: 'HeartPulse' },
  { id: 'cat_8', name: 'Statin / Cholesterol', itemCount: 150, description: 'Lipid-lowering HMG-CoA reductase inhibitors', iconName: 'HeartPulse' },
  { id: 'cat_9', name: 'Thyroid', itemCount: 110, description: 'Hormone replacement and endocrine support', iconName: 'Dna' },
  { id: 'cat_10', name: 'Antiemetic', itemCount: 95, description: 'Nausea and anti-motion sickness medication', iconName: 'Activity' },
  { id: 'cat_11', name: 'Bronchodilator', itemCount: 130, description: 'Airway opening and respiratory distress relief', iconName: 'Wind' },
  { id: 'cat_12', name: 'Anti-allergic', itemCount: 140, description: 'Leukotriene receptor antagonists & anti-allergics', iconName: 'Wind' },
  { id: 'cat_13', name: 'Vitamins / Supplements', itemCount: 380, description: 'Essential multi-nutritional health supplements', iconName: 'Syringe' },
  { id: 'cat_14', name: 'Electrolyte', itemCount: 260, description: 'Rehydration salts and oral electrolyte formulas', iconName: 'Activity' },
  { id: 'cat_15', name: 'Antifungal', itemCount: 175, description: 'Topical and systemic antimycotic agents', iconName: 'Pill' },
  { id: 'cat_16', name: 'Antibiotic / Topical', itemCount: 160, description: 'Topical dermatological antibacterial ointments', iconName: 'Pill' },
  { id: 'cat_17', name: 'Antiseptic', itemCount: 220, description: 'Disinfectant and wound decontamination preparations', iconName: 'Cross' },
  { id: 'cat_18', name: 'Supplement', itemCount: 290, description: 'Calcium, Vitamin D3, and bone mineral fortifiers', iconName: 'Syringe' },
];

export const MOCK_MEDICINES: Medicine[] = [
  {
    id: 'MED-1001',
    name: 'Paracetamol 500mg',
    genericName: 'Paracetamol 500mg',
    brandName: 'Crocin',
    manufacturer: 'Sun Pharma',
    category: 'Analgesic / Antipyretic',
    supplier: 'MedPlus',
    stock: 1200,
    minStockThreshold: 300,
    unit: 'Tab',
    price: 2.00,
    batchNumber: 'BT-CRO500-01',
    manufactureDate: '2025-10-01',
    expiryDate: '2027-10-01',
    location: 'Shelf A-01',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Crocin (Paracetamol 500mg) for fever reduction and mild analgesia.',
  },
  {
    id: 'MED-1002',
    name: 'Paracetamol 650mg',
    genericName: 'Paracetamol 650mg',
    brandName: 'Dolo 650',
    manufacturer: 'Micro Labs',
    category: 'Analgesic / Antipyretic',
    supplier: 'MedPlus',
    stock: 500,
    minStockThreshold: 150,
    unit: 'Tab',
    price: 2.50,
    batchNumber: 'BT-DOLO650-99',
    manufactureDate: '2025-08-15',
    expiryDate: '2027-08-15',
    location: 'Shelf A-02',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=300&auto=format&fit=crop&q=80',
    description: 'Dolo 650 (Paracetamol 650mg) by Micro Labs for acute fever and aches.',
  },
  {
    id: 'MED-1003',
    name: 'Amoxicillin 500mg',
    genericName: 'Amoxicillin 500mg',
    brandName: 'Mox 500',
    manufacturer: 'Sun Pharma',
    category: 'Antibiotic',
    supplier: 'Apollo Pharmacy',
    stock: 1450,
    minStockThreshold: 300,
    unit: 'Cap',
    price: 8.50,
    batchNumber: 'BT-MOX500-12',
    manufactureDate: '2025-11-10',
    expiryDate: '2027-11-10',
    location: 'Shelf A-03',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Mox 500 (Amoxicillin 500mg) broad-spectrum antibiotic capsule.',
  },
  {
    id: 'MED-1004',
    name: 'Azithromycin 500mg',
    genericName: 'Azithromycin 500mg',
    brandName: 'Azithral 500',
    manufacturer: 'Alembic Pharma',
    category: 'Antibiotic',
    supplier: 'PharmEasy',
    stock: 620,
    minStockThreshold: 100,
    unit: 'Tab',
    price: 22.00,
    batchNumber: 'BT-AZI500-04',
    manufactureDate: '2025-09-01',
    expiryDate: '2027-09-01',
    location: 'Shelf A-04',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Azithral 500 macrolide antibiotic for upper respiratory infections.',
  },
  {
    id: 'MED-1005',
    name: 'Cetirizine 10mg',
    genericName: 'Cetirizine 10mg',
    brandName: 'Cetirizine',
    manufacturer: "Dr. Reddy's Laboratories",
    category: 'Antihistamine',
    supplier: '1mg / Tata 1mg',
    stock: 890,
    minStockThreshold: 200,
    unit: 'Tab',
    price: 3.50,
    batchNumber: 'BT-CET10-88',
    manufactureDate: '2025-06-10',
    expiryDate: '2028-06-10',
    location: 'Shelf B-01',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=300&auto=format&fit=crop&q=80',
    description: 'Cetirizine 10mg non-drowsy antihistamine for allergic rhinitis.',
  },
  {
    id: 'MED-1006',
    name: 'Pantoprazole 40mg',
    genericName: 'Pantoprazole 40mg',
    brandName: 'Pantocid 40',
    manufacturer: 'Sun Pharma',
    category: 'Gastrointestinal',
    supplier: 'Netmeds',
    stock: 740,
    minStockThreshold: 150,
    unit: 'Tab',
    price: 9.00,
    batchNumber: 'BT-PAN40-33',
    manufactureDate: '2025-07-20',
    expiryDate: '2027-07-20',
    location: 'Shelf B-02',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Pantocid 40 proton pump inhibitor for GERD and acidity.',
  },
  {
    id: 'MED-1007',
    name: 'Omeprazole 20mg',
    genericName: 'Omeprazole 20mg',
    brandName: 'Omez 20',
    manufacturer: "Dr. Reddy's Laboratories",
    category: 'Gastrointestinal',
    supplier: 'Apollo Pharmacy',
    stock: 98,
    minStockThreshold: 120,
    unit: 'Cap',
    price: 7.00,
    batchNumber: 'BT-OMEZ20-09',
    manufactureDate: '2025-03-01',
    expiryDate: '2026-10-15',
    location: 'Shelf B-03',
    status: 'Low Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Omez 20 capsules for peptic ulcer and gastric acid suppression.',
  },
  {
    id: 'MED-1008',
    name: 'Ibuprofen 400mg',
    genericName: 'Ibuprofen 400mg',
    brandName: 'Brufen 400',
    manufacturer: 'Abbott',
    category: 'NSAID / Pain Relief',
    supplier: 'MedPlus',
    stock: 1800,
    minStockThreshold: 400,
    unit: 'Tab',
    price: 4.00,
    batchNumber: 'BT-BRU400-55',
    manufactureDate: '2025-05-15',
    expiryDate: '2028-05-15',
    location: 'Shelf C-01',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Brufen 400 (Ibuprofen) NSAID for pain, swelling, and inflammation.',
  },
  {
    id: 'MED-1009',
    name: 'Diclofenac 50mg',
    genericName: 'Diclofenac 50mg',
    brandName: 'Voveran 50',
    manufacturer: 'Novartis',
    category: 'NSAID / Pain Relief',
    supplier: 'Sun Pharmaceutical Industries',
    stock: 430,
    minStockThreshold: 100,
    unit: 'Tab',
    price: 6.50,
    batchNumber: 'BT-VOV50-77',
    manufactureDate: '2025-04-10',
    expiryDate: '2027-04-10',
    location: 'Shelf C-02',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Voveran 50 (Diclofenac Sodium) for musculoskeletal pain.',
  },
  {
    id: 'MED-1010',
    name: 'Metformin 500mg',
    genericName: 'Metformin 500mg',
    brandName: 'Glycomet 500',
    manufacturer: 'USV',
    category: 'Antidiabetic',
    supplier: "Dr. Reddy's Laboratories",
    stock: 2100,
    minStockThreshold: 500,
    unit: 'Tab',
    price: 3.00,
    batchNumber: 'BT-GLY500-21',
    manufactureDate: '2025-01-20',
    expiryDate: '2028-01-20',
    location: 'Shelf D-01',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Glycomet 500 (Metformin HCl) first-line type-2 diabetes treatment.',
  },
  {
    id: 'MED-1011',
    name: 'Glimepiride 1mg',
    genericName: 'Glimepiride 1mg',
    brandName: 'Amaryl 1mg',
    manufacturer: 'Sanofi',
    category: 'Antidiabetic',
    supplier: 'Abbott',
    stock: 350,
    minStockThreshold: 80,
    unit: 'Tab',
    price: 5.50,
    batchNumber: 'BT-AMA1-14',
    manufactureDate: '2025-02-14',
    expiryDate: '2027-02-14',
    location: 'Shelf D-02',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Amaryl 1mg sulfonylurea antidiabetic agent for glycemic control.',
  },
  {
    id: 'MED-1012',
    name: 'Amlodipine 5mg',
    genericName: 'Amlodipine 5mg',
    brandName: 'Amlong 5',
    manufacturer: 'Micro Labs',
    category: 'Antihypertensive',
    supplier: 'Alkem Laboratories',
    stock: 1100,
    minStockThreshold: 250,
    unit: 'Tab',
    price: 4.20,
    batchNumber: 'BT-AML5-66',
    manufactureDate: '2025-06-01',
    expiryDate: '2028-06-01',
    location: 'Shelf E-01',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Amlong 5 calcium channel blocker for hypertension & angina.',
  },
  {
    id: 'MED-1013',
    name: 'Losartan 50mg',
    genericName: 'Losartan 50mg',
    brandName: 'Losar 50',
    manufacturer: 'Unichem',
    category: 'Antihypertensive',
    supplier: 'Torrent Pharmaceuticals',
    stock: 670,
    minStockThreshold: 150,
    unit: 'Tab',
    price: 8.00,
    batchNumber: 'BT-LOS50-32',
    manufactureDate: '2025-05-10',
    expiryDate: '2027-05-10',
    location: 'Shelf E-02',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Losar 50 angiotensin II receptor blocker for blood pressure control.',
  },
  {
    id: 'MED-1014',
    name: 'Atorvastatin 10mg',
    genericName: 'Atorvastatin 10mg',
    brandName: 'Atorva 10',
    manufacturer: 'Zydus Lifesciences',
    category: 'Statin / Cholesterol',
    supplier: 'Glenmark Pharmaceuticals',
    stock: 85,
    minStockThreshold: 150,
    unit: 'Tab',
    price: 12.00,
    batchNumber: 'BT-ATO10-82',
    manufactureDate: '2024-11-01',
    expiryDate: '2026-09-01',
    location: 'Shelf E-03',
    status: 'Low Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Atorva 10 lipid-lowering statin for hypercholesterolemia management.',
  },
  {
    id: 'MED-1015',
    name: 'Levothyroxine 50mcg',
    genericName: 'Levothyroxine 50mcg',
    brandName: 'Thyronorm 50',
    manufacturer: 'Abbott',
    category: 'Thyroid',
    supplier: 'Lupin',
    stock: 1600,
    minStockThreshold: 300,
    unit: 'Tab',
    price: 3.80,
    batchNumber: 'BT-THY50-90',
    manufactureDate: '2025-08-01',
    expiryDate: '2028-08-01',
    location: 'Shelf F-01',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Thyronorm 50 synthetic thyroid hormone T4 for hypothyroidism.',
  },
  {
    id: 'MED-1016',
    name: 'Ondansetron 4mg',
    genericName: 'Ondansetron 4mg',
    brandName: 'Ondem 4',
    manufacturer: 'Alkem Laboratories',
    category: 'Antiemetic',
    supplier: 'Mankind Pharma',
    stock: 530,
    minStockThreshold: 100,
    unit: 'Tab',
    price: 11.00,
    batchNumber: 'BT-OND4-11',
    manufactureDate: '2025-07-15',
    expiryDate: '2027-07-15',
    location: 'Shelf F-02',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Ondem 4 serotonin 5-HT3 receptor antagonist for nausea & vomiting.',
  },
  {
    id: 'MED-1017',
    name: 'Domperidone 10mg',
    genericName: 'Domperidone 10mg',
    brandName: 'Domstal 10',
    manufacturer: 'Torrent Pharma',
    category: 'Gastrointestinal',
    supplier: 'Apollo Pharmacy',
    stock: 710,
    minStockThreshold: 150,
    unit: 'Tab',
    price: 4.50,
    batchNumber: 'BT-DOM10-44',
    manufactureDate: '2025-06-20',
    expiryDate: '2027-06-20',
    location: 'Shelf F-03',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Domstal 10 dopamine antagonist prokinetic for upper GI motility.',
  },
  {
    id: 'MED-1018',
    name: 'Salbutamol 4mg',
    genericName: 'Salbutamol 4mg',
    brandName: 'Asthalin',
    manufacturer: 'Cipla',
    category: 'Bronchodilator',
    supplier: 'Cipla',
    stock: 1250,
    minStockThreshold: 200,
    unit: 'Tab',
    price: 15.00,
    batchNumber: 'BT-AST4-05',
    manufactureDate: '2025-09-10',
    expiryDate: '2027-09-10',
    location: 'Shelf G-01',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=300&auto=format&fit=crop&q=80',
    description: 'Asthalin (Salbutamol 4mg) short-acting beta-agonist for asthma.',
  },
  {
    id: 'MED-1019',
    name: 'Montelukast 10mg',
    genericName: 'Montelukast 10mg',
    brandName: 'Montair 10',
    manufacturer: 'Cipla',
    category: 'Anti-allergic',
    supplier: 'PharmEasy',
    stock: 480,
    minStockThreshold: 100,
    unit: 'Tab',
    price: 14.00,
    batchNumber: 'BT-MON10-18',
    manufactureDate: '2025-08-01',
    expiryDate: '2027-08-01',
    location: 'Shelf G-02',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Montair 10 leukotriene receptor antagonist for allergic rhinitis & asthma.',
  },
  {
    id: 'MED-1020',
    name: 'Multivitamin Tablets',
    genericName: 'Multivitamin Tablets',
    brandName: 'Becosules',
    manufacturer: 'Pfizer',
    category: 'Vitamins / Supplements',
    supplier: 'Netmeds',
    stock: 2500,
    minStockThreshold: 500,
    unit: 'Cap',
    price: 5.00,
    batchNumber: 'BT-BEC-77',
    manufactureDate: '2025-05-01',
    expiryDate: '2028-05-01',
    location: 'Shelf H-01',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Becosules B-complex multivitamin capsules with Vitamin C.',
  },
  {
    id: 'MED-1021',
    name: 'ORS Sachet',
    genericName: 'Oral Rehydration Salts',
    brandName: 'Electral',
    manufacturer: 'FDC Limited',
    category: 'Electrolyte',
    supplier: '1mg / Tata 1mg',
    stock: 3200,
    minStockThreshold: 600,
    unit: 'Sachet',
    price: 18.00,
    batchNumber: 'BT-ELE-91',
    manufactureDate: '2025-10-10',
    expiryDate: '2028-10-10',
    location: 'Shelf H-02',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Electral WHO-formula oral rehydration salts for dehydration.',
  },
  {
    id: 'MED-1022',
    name: 'Clotrimazole 1%',
    genericName: 'Clotrimazole 1% Cream',
    brandName: 'Candid Cream',
    manufacturer: 'Glenmark',
    category: 'Antifungal',
    supplier: 'Micro Labs',
    stock: 340,
    minStockThreshold: 80,
    unit: 'Tube',
    price: 45.00,
    batchNumber: 'BT-CAN1-39',
    manufactureDate: '2025-07-01',
    expiryDate: '2027-07-01',
    location: 'Shelf I-01',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Candid Cream (Clotrimazole 1%) broad-spectrum topical antifungal.',
  },
  {
    id: 'MED-1023',
    name: 'Mupirocin 2%',
    genericName: 'Mupirocin 2% Ointment',
    brandName: 'T-Bact',
    manufacturer: 'Glenmark',
    category: 'Antibiotic / Topical',
    supplier: 'MedPlus',
    stock: 210,
    minStockThreshold: 50,
    unit: 'Tube',
    price: 85.00,
    batchNumber: 'BT-TBACT-02',
    manufactureDate: '2025-06-15',
    expiryDate: '2027-06-15',
    location: 'Shelf I-02',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'T-Bact (Mupirocin 2%) topical antibacterial ointment for impetigo.',
  },
  {
    id: 'MED-1024',
    name: 'Povidone-Iodine',
    genericName: 'Povidone-Iodine 10%',
    brandName: 'Betadine',
    manufacturer: 'Win-Medicare',
    category: 'Antiseptic',
    supplier: 'Apollo Pharmacy',
    stock: 580,
    minStockThreshold: 100,
    unit: 'Bottle',
    price: 65.00,
    batchNumber: 'BT-BET10-50',
    manufactureDate: '2025-04-01',
    expiryDate: '2028-04-01',
    location: 'Shelf I-03',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Betadine (Povidone-Iodine 10%) microbicidal topical antiseptic solution.',
  },
  {
    id: 'MED-1025',
    name: 'Calcium + Vitamin D3',
    genericName: 'Calcium Carbonate 500mg + Vit D3 250 IU',
    brandName: 'Shelcal 500',
    manufacturer: 'Torrent Pharma',
    category: 'Supplement',
    supplier: 'Torrent Pharmaceuticals',
    stock: 1400,
    minStockThreshold: 300,
    unit: 'Tab',
    price: 10.50,
    batchNumber: 'BT-SHE500-11',
    manufactureDate: '2025-09-01',
    expiryDate: '2028-09-01',
    location: 'Shelf J-01',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Shelcal 500 (Calcium + Vitamin D3) for bone mineral density support.',
  },
  {
    id: 'MED-1026',
    name: 'Doxycycline 100mg',
    genericName: 'Doxycycline 100mg Hyclate',
    brandName: 'Doxicip 100',
    manufacturer: 'Cipla',
    category: 'Antibiotic',
    supplier: 'Cipla',
    stock: 140,
    minStockThreshold: 50,
    unit: 'Cap',
    price: 12.00,
    batchNumber: 'BT-DOX100-EXP',
    manufactureDate: '2024-08-01',
    expiryDate: '2026-08-01',
    location: 'Shelf B-04',
    status: 'Expired',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Doxicip 100 broad-spectrum tetracycline antibiotic (Batch Expired - Immediate Disposal Required).',
  },
  {
    id: 'MED-1027',
    name: 'Levofloxacin 500mg',
    genericName: 'Levofloxacin 500mg',
    brandName: 'Loxof 500',
    manufacturer: 'Ranbaxy',
    category: 'Antibiotic',
    supplier: 'Sun Pharmaceutical Industries',
    stock: 280,
    minStockThreshold: 80,
    unit: 'Tab',
    price: 18.50,
    batchNumber: 'BT-LOX500-NEXP',
    manufactureDate: '2025-02-10',
    expiryDate: '2026-08-25',
    location: 'Shelf B-05',
    status: 'Near Expiry',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Loxof 500 fluoroquinolone antibiotic for respiratory infections (Critical Expiration Window).',
  },
];

export const MOCK_SUPPLIERS: Supplier[] = [
  { id: 'SUP-01', name: 'Apollo Pharmacy', contactPerson: 'Rajesh Kumar', email: 'procurement@apollopharmacy.in', phone: '+91 800-200-1122', address: 'Apollo Logistics Hub, Chennai, TN', category: 'Retail & Institutional Supply', performanceScore: 98.5, activeOrders: 5, totalSupplied: 450000, status: 'Preferred', rating: 4.9 },
  { id: 'SUP-02', name: 'MedPlus', contactPerson: 'Suresh Reddy', email: 'orders@medplusindia.com', phone: '+91 800-425-0000', address: 'MedPlus Wholesale Hub, Hyderabad, TS', category: 'Pharma Retail & Wholesale', performanceScore: 97.2, activeOrders: 4, totalSupplied: 380000, status: 'Preferred', rating: 4.8 },
  { id: 'SUP-03', name: 'PharmEasy', contactPerson: 'Anish Sharma', email: 'supply@pharmeasy.in', phone: '+91 800-120-8888', address: 'PharmEasy Fulfillment Center, Mumbai, MH', category: 'Digital & Express Logistics', performanceScore: 95.8, activeOrders: 3, totalSupplied: 290000, status: 'Active', rating: 4.7 },
  { id: 'SUP-04', name: '1mg / Tata 1mg', contactPerson: 'Priya Nair', email: 'b2b@1mg.com', phone: '+91 800-300-9999', address: 'Tata 1mg Warehouse Depot, Gurgaon, HR', category: 'Enterprise Healthcare Supply', performanceScore: 96.9, activeOrders: 4, totalSupplied: 340000, status: 'Preferred', rating: 4.8 },
  { id: 'SUP-05', name: 'Netmeds', contactPerson: 'Venkatesh Iyer', email: 'distributors@netmeds.com', phone: '+91 800-540-3333', address: 'Netmeds Logistics Park, Chennai, TN', category: 'National Pharma Wholesale', performanceScore: 94.5, activeOrders: 2, totalSupplied: 210000, status: 'Active', rating: 4.6 },
  { id: 'SUP-06', name: 'Cipla', contactPerson: 'Dr. Yusuf Hamied', email: 'institutional@cipla.com', phone: '+91 22-2482-6000', address: 'Cipla House, Peninsula Business Park, Mumbai, MH', category: 'Manufacturer Direct & Respiratory', performanceScore: 99.1, activeOrders: 6, totalSupplied: 620000, status: 'Preferred', rating: 5.0 },
  { id: 'SUP-07', name: 'Sun Pharmaceutical Industries', contactPerson: 'Amitabh Gupta', email: 'sales@sunpharma.com', phone: '+91 22-4324-4324', address: 'Sun House, Goregaon East, Mumbai, MH', category: 'Manufacturer Direct & Generics', performanceScore: 98.8, activeOrders: 7, totalSupplied: 750000, status: 'Preferred', rating: 4.9 },
  { id: 'SUP-08', name: "Dr. Reddy's Laboratories", contactPerson: 'K. Satish Reddy', email: 'corporate@drreddys.com', phone: '+91 40-4900-2900', address: 'Greenlands, Ameerpet, Hyderabad, TS', category: 'API & Formulation Supply', performanceScore: 98.2, activeOrders: 5, totalSupplied: 580000, status: 'Preferred', rating: 4.9 },
  { id: 'SUP-09', name: 'Abbott', contactPerson: 'Vikram Shroff', email: 'orders@abbott.co.in', phone: '+91 22-3816-2000', address: 'Godrej BKC, Bandra East, Mumbai, MH', category: 'Global Healthcare & Nutrition', performanceScore: 97.4, activeOrders: 3, totalSupplied: 420000, status: 'Preferred', rating: 4.8 },
  { id: 'SUP-10', name: 'Alkem Laboratories', contactPerson: 'Sandeep Singh', email: 'b2b@alkem.com', phone: '+91 22-3982-9999', address: 'Alkem House, Senapati Bapat Marg, Mumbai, MH', category: 'Anti-infectives & Gastroenterology', performanceScore: 95.0, activeOrders: 2, totalSupplied: 310000, status: 'Active', rating: 4.6 },
  { id: 'SUP-11', name: 'Zydus Lifesciences', contactPerson: 'Pankaj Patel', email: 'contact@zyduslife.com', phone: '+91 79-4804-0000', address: 'Zydus Corporate Park, Ahmedabad, GJ', category: 'Cardiovascular & Biosimilars', performanceScore: 96.0, activeOrders: 3, totalSupplied: 390000, status: 'Active', rating: 4.7 },
  { id: 'SUP-12', name: 'Torrent Pharmaceuticals', contactPerson: 'Samir Mehta', email: 'supply@torrentpharma.com', phone: '+91 79-2686-6666', address: 'Torrent House, Ashram Road, Ahmedabad, GJ', category: 'CNS, Cardiac & Gastro', performanceScore: 96.5, activeOrders: 3, totalSupplied: 360000, status: 'Active', rating: 4.7 },
  { id: 'SUP-13', name: 'Glenmark Pharmaceuticals', contactPerson: 'Glenn Saldanha', email: 'institutional@glenmarkpharma.com', phone: '+91 22-4018-9999', address: 'Glenmark House, B.D. Sawant Marg, Mumbai, MH', category: 'Dermatology & Respiratory', performanceScore: 95.5, activeOrders: 2, totalSupplied: 280000, status: 'Active', rating: 4.6 },
  { id: 'SUP-14', name: 'Micro Labs', contactPerson: 'Dilip Surana', email: 'orders@microlabs.in', phone: '+91 80-2225-1509', address: 'Micro Labs House, Race Course Road, Bengaluru, KA', category: 'Cardiology & Pain Management', performanceScore: 97.9, activeOrders: 4, totalSupplied: 490000, status: 'Preferred', rating: 4.8 },
  { id: 'SUP-15', name: 'Lupin', contactPerson: 'Nilesh Gupta', email: 'info@lupin.com', phone: '+91 22-6640-2222', address: 'Kalpataru Inspire, BKC, Mumbai, MH', category: 'Anti-TB & Diabetology', performanceScore: 96.3, activeOrders: 3, totalSupplied: 330000, status: 'Active', rating: 4.7 },
  { id: 'SUP-16', name: 'Mankind Pharma', contactPerson: 'Rajeev Juneja', email: 'contact@mankindpharma.com', phone: '+91 11-4654-1111', address: 'Mankind House, Okhla Phase III, New Delhi', category: 'Consumer Healthcare & Formulations', performanceScore: 95.2, activeOrders: 2, totalSupplied: 270000, status: 'Active', rating: 4.6 },
];

export const MOCK_ORDERS: PurchaseOrder[] = [
  {
    id: 'PO-2026-8801',
    orderNumber: 'PO-8801',
    supplierId: 'SUP-02',
    supplierName: 'MedPlus',
    medicineName: 'Paracetamol 650mg',
    assignedPharmacistName: 'John Doe',
    assignedPharmacistEmail: 'pharmacist@medistock.com',
    itemsCount: 10000,
    quantity: 10000,
    pricePerUnit: 2.50,
    totalAmount: 25000.00,
    status: 'Pending',
    orderedDate: '2026-08-10',
    expectedDelivery: '2026-08-15',
    batchNumber: 'BT-DOLO650-99',
    expiryDate: '2027-08-15',
    createdByName: 'John Doe',
  },
  {
    id: 'PO-2026-8802',
    orderNumber: 'PO-8802',
    supplierId: 'SUP-01',
    supplierName: 'Apollo Pharmacy',
    medicineName: 'Amoxicillin 500mg',
    assignedPharmacistName: 'Dr. Sarah Jenkins',
    assignedPharmacistEmail: 'sarah.jenkins@medistock.health',
    itemsCount: 5000,
    quantity: 5000,
    pricePerUnit: 8.50,
    totalAmount: 42500.00,
    status: 'Approved',
    orderedDate: '2026-08-08',
    expectedDelivery: '2026-08-14',
    batchNumber: 'BT-MOX500-12',
    expiryDate: '2027-11-10',
    createdByName: 'Dr. Sarah Jenkins',
  },
  {
    id: 'PO-2026-8803',
    orderNumber: 'PO-8803',
    supplierId: 'SUP-03',
    supplierName: 'PharmEasy',
    medicineName: 'Azithromycin 500mg',
    assignedPharmacistName: 'John Doe',
    assignedPharmacistEmail: 'pharmacist@medistock.com',
    itemsCount: 2000,
    quantity: 2000,
    pricePerUnit: 22.00,
    totalAmount: 44000.00,
    status: 'Shipped',
    orderedDate: '2026-08-05',
    expectedDelivery: '2026-08-13',
    batchNumber: 'BT-AZI500-04',
    expiryDate: '2027-09-01',
    createdByName: 'System Admin',
  },
  {
    id: 'PO-2026-8804',
    orderNumber: 'PO-8804',
    supplierId: 'SUP-02',
    supplierName: 'MedPlus',
    medicineName: 'Paracetamol 500mg',
    assignedPharmacistName: 'John Doe',
    assignedPharmacistEmail: 'pharmacist@medistock.com',
    itemsCount: 12000,
    quantity: 12000,
    pricePerUnit: 2.00,
    totalAmount: 24000.00,
    status: 'Delivered',
    orderedDate: '2026-07-28',
    expectedDelivery: '2026-08-02',
    batchNumber: 'BT-CRO500-01',
    expiryDate: '2027-10-01',
    createdByName: 'John Doe',
  },
  {
    id: 'PO-2026-8805',
    orderNumber: 'PO-8805',
    supplierId: 'SUP-05',
    supplierName: 'Netmeds',
    medicineName: 'Pantoprazole 40mg',
    assignedPharmacistName: 'Dr. Sarah Jenkins',
    assignedPharmacistEmail: 'sarah.jenkins@medistock.health',
    itemsCount: 3000,
    quantity: 3000,
    pricePerUnit: 9.00,
    totalAmount: 27000.00,
    status: 'Pending',
    orderedDate: '2026-08-11',
    expectedDelivery: '2026-08-16',
    batchNumber: 'BT-PAN40-33',
    expiryDate: '2027-07-20',
    createdByName: 'Dr. Sarah Jenkins',
  },
  {
    id: 'PO-2026-8806',
    orderNumber: 'PO-8806',
    supplierId: 'SUP-04',
    supplierName: '1mg / Tata 1mg',
    medicineName: 'Cetirizine 10mg',
    assignedPharmacistName: 'John Doe',
    assignedPharmacistEmail: 'pharmacist@medistock.com',
    itemsCount: 4000,
    quantity: 4000,
    pricePerUnit: 3.50,
    totalAmount: 14000.00,
    status: 'Approved',
    orderedDate: '2026-08-09',
    expectedDelivery: '2026-08-14',
    batchNumber: 'BT-CET10-88',
    expiryDate: '2028-06-10',
    createdByName: 'System Admin',
  },
  {
    id: 'PO-2026-8807',
    orderNumber: 'PO-8807',
    supplierId: 'SUP-06',
    supplierName: 'Cipla',
    medicineName: 'Salbutamol 4mg',
    assignedPharmacistName: 'Dr. Sarah Jenkins',
    assignedPharmacistEmail: 'sarah.jenkins@medistock.health',
    itemsCount: 5000,
    quantity: 5000,
    pricePerUnit: 15.00,
    totalAmount: 75000.00,
    status: 'Shipped',
    orderedDate: '2026-08-06',
    expectedDelivery: '2026-08-13',
    batchNumber: 'BT-AST4-05',
    expiryDate: '2027-09-10',
    createdByName: 'Dr. Sarah Jenkins',
  },
  {
    id: 'PO-2026-8808',
    orderNumber: 'PO-8808',
    supplierId: 'SUP-08',
    supplierName: "Dr. Reddy's Laboratories",
    medicineName: 'Metformin 500mg',
    assignedPharmacistName: 'John Doe',
    assignedPharmacistEmail: 'pharmacist@medistock.com',
    itemsCount: 15000,
    quantity: 15000,
    pricePerUnit: 3.00,
    totalAmount: 45000.00,
    status: 'Delivered',
    orderedDate: '2026-07-25',
    expectedDelivery: '2026-08-01',
    batchNumber: 'BT-GLY500-21',
    expiryDate: '2028-01-20',
    createdByName: 'John Doe',
  },
  {
    id: 'PO-2026-8809',
    orderNumber: 'PO-8809',
    supplierId: 'SUP-12',
    supplierName: 'Torrent Pharmaceuticals',
    medicineName: 'Calcium + Vitamin D3',
    assignedPharmacistName: 'Dr. Sarah Jenkins',
    assignedPharmacistEmail: 'sarah.jenkins@medistock.health',
    itemsCount: 4000,
    quantity: 4000,
    pricePerUnit: 10.50,
    totalAmount: 42000.00,
    status: 'Pending',
    orderedDate: '2026-08-11',
    expectedDelivery: '2026-08-17',
    batchNumber: 'BT-SHE500-11',
    expiryDate: '2028-09-01',
    createdByName: 'Dr. Sarah Jenkins',
  },
  {
    id: 'PO-2026-8810',
    orderNumber: 'PO-8810',
    supplierId: 'SUP-09',
    supplierName: 'Abbott',
    medicineName: 'Ibuprofen 400mg',
    assignedPharmacistName: 'John Doe',
    assignedPharmacistEmail: 'pharmacist@medistock.com',
    itemsCount: 8000,
    quantity: 8000,
    pricePerUnit: 4.00,
    totalAmount: 32000.00,
    status: 'Shipped',
    orderedDate: '2026-08-07',
    expectedDelivery: '2026-08-14',
    batchNumber: 'BT-BRU400-55',
    expiryDate: '2028-05-15',
    createdByName: 'System Admin',
  },
];

export const MOCK_STOCK_LOGS: StockLog[] = [
  {
    id: 'LOG-9941',
    medicineId: 'MED-1001',
    medicineName: 'Amoxicillin Trihydrate',
    type: 'Stock In',
    quantity: 500,
    previousStock: 950,
    newStock: 1450,
    performedBy: 'David Chen',
    timestamp: '2026-07-27 10:14:00',
    reason: 'Received shipment batch BT-88921 from BioPharma',
  },
  {
    id: 'LOG-9940',
    medicineId: 'MED-1003',
    medicineName: 'Lantus SoloStar Insulin',
    type: 'Stock Out',
    quantity: 6,
    previousStock: 30,
    newStock: 24,
    performedBy: 'Dr. Sarah Jenkins',
    timestamp: '2026-07-27 09:30:00',
    reason: 'Dispensed to Ward B Intensive Care Unit',
  },
  {
    id: 'LOG-9939',
    medicineId: 'MED-1005',
    medicineName: 'EpiPen Auto-Injector 0.3mg',
    type: 'Stock Out',
    quantity: 10,
    previousStock: 10,
    newStock: 0,
    performedBy: 'Elena Rostova',
    timestamp: '2026-07-26 16:45:00',
    reason: 'Emergency ER replenishment callout',
  },
  {
    id: 'LOG-9938',
    medicineId: 'MED-1008',
    medicineName: 'Comirnaty COVID-19 Vaccine',
    type: 'Disposed',
    quantity: 15,
    previousStock: 33,
    newStock: 18,
    performedBy: 'Marcus Vance',
    timestamp: '2026-07-25 14:10:00',
    reason: 'Cold chain temperature deviation write-off',
  },
  {
    id: 'LOG-9937',
    medicineId: 'MED-1007',
    medicineName: 'Ibuprofen 400mg Ultra',
    type: 'Adjustment',
    quantity: 200,
    previousStock: 2000,
    newStock: 2200,
    performedBy: 'Amara Okafor',
    timestamp: '2026-07-24 11:20:00',
    reason: 'Routine quarterly audit reconciliation',
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Out of Stock Alert',
    message: 'EpiPen Auto-Injector 0.3mg reached 0 units. Immediate reorder suggested.',
    timestamp: '10 mins ago',
    type: 'alert',
    read: false,
    category: 'Stock',
  },
  {
    id: 'notif-2',
    title: 'Near Expiry Notice',
    message: 'Lantus SoloStar Insulin (Batch BT-90112) expires in 19 days.',
    timestamp: '1 hour ago',
    type: 'warning',
    read: false,
    category: 'Expiry',
  },
  {
    id: 'notif-3',
    title: 'Shipment Dispatched',
    message: 'Purchase Order PO-8802 (Pfizer Direct) is now in transit.',
    timestamp: '3 hours ago',
    type: 'info',
    read: true,
    category: 'Order',
  },
  {
    id: 'notif-4',
    title: 'Stock Audit Verified',
    message: 'Quarterly inventory audit for Antibiotics finished with 99.8% precision.',
    timestamp: 'Yesterday',
    type: 'success',
    read: true,
    category: 'System',
  },
];

export const MOCK_MONTHLY_ANALYTICS = [
  { month: 'Jan', stockIn: 4500, stockOut: 3200, orders: 12000 },
  { month: 'Feb', stockIn: 5200, stockOut: 3900, orders: 15400 },
  { month: 'Mar', stockIn: 6100, stockOut: 4400, orders: 18900 },
  { month: 'Apr', stockIn: 5800, stockOut: 4800, orders: 16200 },
  { month: 'May', stockIn: 7400, stockOut: 5300, orders: 22100 },
  { month: 'Jun', stockIn: 6900, stockOut: 5600, orders: 20400 },
  { month: 'Jul', stockIn: 8300, stockOut: 6100, orders: 25800 },
];
