import type { ResourceConfig, FilterConfig } from "./ResourceManager";

const ref = (endpoint: string, label: string) => ({ endpoint, label });
export const resources: Record<string, ResourceConfig> = {
  medicines: { title: "Medicines", singular: "Medicine", endpoint: "/medicines", searchEndpoint: "/medicines/search", fields: [{ key: "name", label: "Name", required: true }, { key: "description", label: "Description" }, { key: "category", label: "Category" }, { key: "price", label: "Price", type: "number", required: true }, { key: "supplier", label: "Supplier", reference: ref("/suppliers", "name") }], filters: [{ key: "category", label: "Category", endpoint: "/medicines/filter/category", param: "category", type: "dynamic", dynamicKey: "category" }, { key: "supplier", label: "Supplier", endpoint: "/medicines/filter/supplier", param: "supplierId", type: "reference", reference: ref("/suppliers", "name") }, { key: "stock", label: "Stock Status", endpoint: "/medicines/filter/stock", param: "status", type: "select", options: [{ label: "Available", value: "available" }, { label: "Low Stock", value: "low" }] }] },
  suppliers: { title: "Suppliers", singular: "Supplier", endpoint: "/suppliers", fields: [{ key: "name", label: "Name", required: true }, { key: "contact", label: "Contact" }, { key: "email", label: "Email" }] },
  inventory: { title: "Inventory", singular: "Stock batch", endpoint: "/inventories", special: "inventory", fields: [{ key: "medicine", label: "Medicine", required: true, reference: ref("/medicines", "name") }, { key: "batchNumber", label: "Batch number" }, { key: "quantity", label: "Quantity", type: "number", required: true }, { key: "expiryDate", label: "Expiry date", type: "date" }] },
  purchases: { title: "Purchase Orders", singular: "Purchase order", endpoint: "/purchaseorders", fields: [{ key: "supplier", label: "Supplier", required: true, reference: ref("/suppliers", "name") }, { key: "orderDate", label: "Order date", type: "datetime-local" }, { key: "status", label: "Status", type: "select", options: ["PENDING", "COMPLETED", "CANCELLED"] }] },
  purchaseItems: { title: "Purchase Order Items", singular: "Purchase item", endpoint: "/purchaseorderitems", fields: [{ key: "purchaseOrder", label: "Order", required: true, reference: ref("/purchaseorders", "id") }, { key: "medicine", label: "Medicine", required: true, reference: ref("/medicines", "name") }, { key: "quantity", label: "Quantity", type: "number", required: true }, { key: "price", label: "Price", type: "number" }] },
  reports: { title: "Reports", singular: "Report", endpoint: "/reports", fields: [{ key: "type", label: "Type", required: true, type: "select", options: ["INVENTORY", "SALES", "EXPIRY"] }, { key: "generatedDate", label: "Generated date", type: "datetime-local" }, { key: "fileUrl", label: "File URL" }] },
  users: { title: "Users", singular: "User", endpoint: "/users", fields: [{ key: "username", label: "Username", required: true }, { key: "email", label: "Email", required: true }, { key: "password", label: "Password", required: true }, { key: "role", label: "Role", required: true, reference: ref("/roles", "name") }] },
  roles: { title: "Roles", singular: "Role", endpoint: "/roles", fields: [{ key: "name", label: "Role name", required: true }] },
  stockLogs: { title: "Stock Activity", singular: "Stock log", endpoint: "/stocklogs", fields: [{ key: "medicine", label: "Medicine", required: true, reference: ref("/medicines", "name") }, { key: "user", label: "User", required: true, reference: ref("/users", "username") }, { key: "action", label: "Action", required: true, type: "select", options: ["ADD", "REMOVE", "UPDATE"] }, { key: "quantity", label: "Quantity", required: true, type: "number" }, { key: "timestamp", label: "Time", type: "datetime-local" }] },
  notifications: { title: "Notifications", singular: "Notification", endpoint: "/notifications", special: "notifications", fields: [{ key: "user", label: "User", required: true, reference: ref("/users", "username") }, { key: "message", label: "Message", required: true }, { key: "isRead", label: "Read", type: "boolean" }, { key: "timestamp", label: "Time", type: "datetime-local" }] },
  expiries: { title: "Expiry Tracking", singular: "Expiry record", endpoint: "/expirys", special: "expiries", fields: [{ key: "medicineName", label: "Medicine Name", required: true }, { key: "expiryDate", label: "Expiry Date", type: "date", required: true }, { key: "status", label: "Status", type: "select", options: ["Expired", "Near Expiry"] }] },
};
