spring:
  application:
    name: medistock-backend
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-dummy-client-id
            client-secret: google-dummy-client-secret
            scope:
              - email
              - profile
          github:
            client-id: github-dummy-client-id
            client-secret: github-dummy-client-secret
            scope:
              - user:email
              - read:user

  # PostgreSQL Datasource Configuration
  datasource:
    url: jdbc:postgresql://postgresdb:5432/medistock_db
    username: postgres
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Hibernate JPA Configuration
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Flyway Database Migration Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    repair-on-migrate: true
    locations: classpath:db/migration

server:
  port: ${PORT:8080}
