// Generated by delombok at Mon Aug 03 06:19:19 IST 2026
package com.medistock.medistockbackend.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;
import java.util.List;

@Entity
@Table(name = "purchase_orders")
public class PurchaseOrder {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne
    @JoinColumn(name = "supplier_id", nullable = false)
    private Supplier supplier;
    private LocalDateTime orderDate = LocalDateTime.now();
    private String status; // e.g., PENDING, COMPLETED, CANCELLED
    @OneToMany(mappedBy = "purchaseOrder", cascade = CascadeType.ALL)
    private List<PurchaseOrderItem> items;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Supplier getSupplier() {
        return this.supplier;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getOrderDate() {
        return this.orderDate;
    }

    @java.lang.SuppressWarnings("all")
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public List<PurchaseOrderItem> getItems() {
        return this.items;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setSupplier(final Supplier supplier) {
        this.supplier = supplier;
    }

    @java.lang.SuppressWarnings("all")
    public void setOrderDate(final LocalDateTime orderDate) {
        this.orderDate = orderDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setItems(final List<PurchaseOrderItem> items) {
        this.items = items;
    }

    @java.lang.SuppressWarnings("all")
    public PurchaseOrder() {
    }

    @java.lang.SuppressWarnings("all")
    public PurchaseOrder(final Long id, final Supplier supplier, final LocalDateTime orderDate, final String status, final List<PurchaseOrderItem> items) {
        this.id = id;
        this.supplier = supplier;
        this.orderDate = orderDate;
        this.status = status;
        this.items = items;
    }
}
