// Generated by delombok at Mon Aug 03 06:19:19 IST 2026
package com.medistock.medistockbackend.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "reports")
public class Report {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String type; // e.g., INVENTORY, SALES, EXPIRY
    private LocalDateTime generatedDate = LocalDateTime.now();
    private String fileUrl;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getGeneratedDate() {
        return this.generatedDate;
    }

    @java.lang.SuppressWarnings("all")
    public String getFileUrl() {
        return this.fileUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setType(final String type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    public void setGeneratedDate(final LocalDateTime generatedDate) {
        this.generatedDate = generatedDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setFileUrl(final String fileUrl) {
        this.fileUrl = fileUrl;
    }

    @java.lang.SuppressWarnings("all")
    public Report() {
    }

    @java.lang.SuppressWarnings("all")
    public Report(final Long id, final String type, final LocalDateTime generatedDate, final String fileUrl) {
        this.id = id;
        this.type = type;
        this.generatedDate = generatedDate;
        this.fileUrl = fileUrl;
    }
}
