// Generated by delombok at Mon Aug 03 06:24:16 IST 2026
package com.medistock.medistockbackend.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "expiry_trackings")
public class ExpiryTracking {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @OneToOne
    @JoinColumn(name = "inventory_id", nullable = false)
    private Inventory inventory;
    private Integer daysToExpiry;
    private String status; // e.g., EXPIRED, EXPIRING_SOON, SAFE

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Inventory getInventory() {
        return this.inventory;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getDaysToExpiry() {
        return this.daysToExpiry;
    }

    @java.lang.SuppressWarnings("all")
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setInventory(final Inventory inventory) {
        this.inventory = inventory;
    }

    @java.lang.SuppressWarnings("all")
    public void setDaysToExpiry(final Integer daysToExpiry) {
        this.daysToExpiry = daysToExpiry;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public ExpiryTracking() {
    }

    @java.lang.SuppressWarnings("all")
    public ExpiryTracking(final Long id, final Inventory inventory, final Integer daysToExpiry, final String status) {
        this.id = id;
        this.inventory = inventory;
        this.daysToExpiry = daysToExpiry;
        this.status = status;
    }
}
