// Generated by delombok at Mon Aug 03 06:24:16 IST 2026
package com.medistock.medistockbackend.entity;

import jakarta.persistence.*;
import java.time.LocalDate;

@Entity
@Table(name = "inventory")
public class Inventory {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "inventory_id")
    private Long id;
    @ManyToOne
    @JoinColumn(name = "medicine_id", nullable = false)
    private Medicine medicine;
    private String batchNumber;
    @Column(nullable = false)
    private Integer quantity;
    private LocalDate expiryDate;

    @Column(name = "minimum_stock")
    private Integer minimumStock;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Medicine getMedicine() {
        return this.medicine;
    }

    @java.lang.SuppressWarnings("all")
    public String getBatchNumber() {
        return this.batchNumber;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getQuantity() {
        return this.quantity;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getExpiryDate() {
        return this.expiryDate;
    }


    @java.lang.SuppressWarnings("all")
    public Integer getMinimumStock() {
        return this.minimumStock;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setMedicine(final Medicine medicine) {
        this.medicine = medicine;
    }

    @java.lang.SuppressWarnings("all")
    public void setBatchNumber(final String batchNumber) {
        this.batchNumber = batchNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setQuantity(final Integer quantity) {
        this.quantity = quantity;
    }

    @java.lang.SuppressWarnings("all")
    public void setExpiryDate(final LocalDate expiryDate) {
        this.expiryDate = expiryDate;
    }


    @java.lang.SuppressWarnings("all")
    public void setMinimumStock(final Integer minimumStock) {
        this.minimumStock = minimumStock;
    }

    @java.lang.SuppressWarnings("all")
    public Inventory() {
    }

    @java.lang.SuppressWarnings("all")
    public Inventory(final Long id, final Medicine medicine, final String batchNumber, final Integer quantity, final LocalDate expiryDate, final Integer minimumStock) {
        this.id = id;
        this.medicine = medicine;
        this.batchNumber = batchNumber;
        this.quantity = quantity;
        this.expiryDate = expiryDate;
        this.minimumStock = minimumStock;
    }
}
