// Generated by delombok at Mon Aug 03 06:24:16 IST 2026
package com.medistock.medistockbackend.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import java.time.LocalDate;

@Entity
@Table(name = "inventories")
public class Inventory {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne
    @JoinColumn(name = "medicine_id", nullable = false)
    private Medicine medicine;
    private String batchNumber;
    @Column(nullable = false)
    private Integer quantity;
    private LocalDate expiryDate;
    @JsonIgnore
    @OneToOne(mappedBy = "inventory", cascade = CascadeType.ALL)
    private ExpiryTracking expiryTracking;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Medicine getMedicine() {
        return this.medicine;
    }

    @java.lang.SuppressWarnings("all")
    public String getBatchNumber() {
        return this.batchNumber;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getQuantity() {
        return this.quantity;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getExpiryDate() {
        return this.expiryDate;
    }

    @java.lang.SuppressWarnings("all")
    public ExpiryTracking getExpiryTracking() {
        return this.expiryTracking;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setMedicine(final Medicine medicine) {
        this.medicine = medicine;
    }

    @java.lang.SuppressWarnings("all")
    public void setBatchNumber(final String batchNumber) {
        this.batchNumber = batchNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setQuantity(final Integer quantity) {
        this.quantity = quantity;
    }

    @java.lang.SuppressWarnings("all")
    public void setExpiryDate(final LocalDate expiryDate) {
        this.expiryDate = expiryDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setExpiryTracking(final ExpiryTracking expiryTracking) {
        this.expiryTracking = expiryTracking;
    }

    @java.lang.SuppressWarnings("all")
    public Inventory() {
    }

    @java.lang.SuppressWarnings("all")
    public Inventory(final Long id, final Medicine medicine, final String batchNumber, final Integer quantity, final LocalDate expiryDate, final ExpiryTracking expiryTracking) {
        this.id = id;
        this.medicine = medicine;
        this.batchNumber = batchNumber;
        this.quantity = quantity;
        this.expiryDate = expiryDate;
        this.expiryTracking = expiryTracking;
    }
}
