// Generated by delombok at Mon Aug 03 06:24:16 IST 2026
package com.medistock.medistockbackend.entity;

import jakarta.persistence.*;
import java.util.List;

@Entity
@Table(name = "medicines")
public class Medicine {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String name;
    private String description;
    @Column(nullable = false)
    private Double price;
    @ManyToOne
    @JoinColumn(name = "supplier_id")
    private Supplier supplier;
    @OneToMany(mappedBy = "medicine", cascade = CascadeType.ALL)
    private List<Inventory> inventories;
    @OneToMany(mappedBy = "medicine", cascade = CascadeType.ALL)
    private List<StockLog> stockLogs;
    @OneToMany(mappedBy = "medicine", cascade = CascadeType.ALL)
    private List<PurchaseOrderItem> purchaseOrderItems;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public Double getPrice() {
        return this.price;
    }

    @java.lang.SuppressWarnings("all")
    public Supplier getSupplier() {
        return this.supplier;
    }

    @java.lang.SuppressWarnings("all")
    public List<Inventory> getInventories() {
        return this.inventories;
    }

    @java.lang.SuppressWarnings("all")
    public List<StockLog> getStockLogs() {
        return this.stockLogs;
    }

    @java.lang.SuppressWarnings("all")
    public List<PurchaseOrderItem> getPurchaseOrderItems() {
        return this.purchaseOrderItems;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setPrice(final Double price) {
        this.price = price;
    }

    @java.lang.SuppressWarnings("all")
    public void setSupplier(final Supplier supplier) {
        this.supplier = supplier;
    }

    @java.lang.SuppressWarnings("all")
    public void setInventories(final List<Inventory> inventories) {
        this.inventories = inventories;
    }

    @java.lang.SuppressWarnings("all")
    public void setStockLogs(final List<StockLog> stockLogs) {
        this.stockLogs = stockLogs;
    }

    @java.lang.SuppressWarnings("all")
    public void setPurchaseOrderItems(final List<PurchaseOrderItem> purchaseOrderItems) {
        this.purchaseOrderItems = purchaseOrderItems;
    }

    @java.lang.SuppressWarnings("all")
    public Medicine() {
    }

    @java.lang.SuppressWarnings("all")
    public Medicine(final Long id, final String name, final String description, final Double price, final Supplier supplier, final List<Inventory> inventories, final List<StockLog> stockLogs, final List<PurchaseOrderItem> purchaseOrderItems) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.price = price;
        this.supplier = supplier;
        this.inventories = inventories;
        this.stockLogs = stockLogs;
        this.purchaseOrderItems = purchaseOrderItems;
    }
}
