// Generated by delombok at Mon Aug 03 06:24:16 IST 2026
package com.medistock.medistockbackend.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "notifications")
public class Notification {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @Column(nullable = false)
    private String message;
    private Boolean isRead = false;
    private LocalDateTime timestamp = LocalDateTime.now();

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getIsRead() {
        return this.isRead;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.SuppressWarnings("all")
    public void setIsRead(final Boolean isRead) {
        this.isRead = isRead;
    }

    @java.lang.SuppressWarnings("all")
    public void setTimestamp(final LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    @java.lang.SuppressWarnings("all")
    public Notification() {
    }

    @java.lang.SuppressWarnings("all")
    public Notification(final Long id, final User user, final String message, final Boolean isRead, final LocalDateTime timestamp) {
        this.id = id;
        this.user = user;
        this.message = message;
        this.isRead = isRead;
        this.timestamp = timestamp;
    }
}
