// Generated by delombok at Mon Aug 03 06:24:16 IST 2026
package com.medistock.medistockbackend.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import java.util.List;

@Entity
@Table(name = "roles")
public class Role {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false, unique = true)
    private String name;
    @JsonIgnore
    @OneToMany(mappedBy = "role", cascade = CascadeType.ALL)
    private List<User> users;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public List<User> getUsers() {
        return this.users;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setUsers(final List<User> users) {
        this.users = users;
    }

    @java.lang.SuppressWarnings("all")
    public Role() {
    }

    @java.lang.SuppressWarnings("all")
    public Role(final Long id, final String name, final List<User> users) {
        this.id = id;
        this.name = name;
        this.users = users;
    }
}
