// Generated by delombok at Mon Aug 03 06:24:16 IST 2026
package com.medistock.medistockbackend.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import java.util.List;

@Entity
@Table(name = "suppliers")
public class Supplier {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String name;
    private String contact;
    private String email;
    @JsonIgnore
    @OneToMany(mappedBy = "supplier", cascade = CascadeType.ALL)
    private List<Medicine> medicines;
    @JsonIgnore
    @OneToMany(mappedBy = "supplier", cascade = CascadeType.ALL)
    private List<PurchaseOrder> purchaseOrders;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getContact() {
        return this.contact;
    }

    @java.lang.SuppressWarnings("all")
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    public List<Medicine> getMedicines() {
        return this.medicines;
    }

    @java.lang.SuppressWarnings("all")
    public List<PurchaseOrder> getPurchaseOrders() {
        return this.purchaseOrders;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setContact(final String contact) {
        this.contact = contact;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    public void setMedicines(final List<Medicine> medicines) {
        this.medicines = medicines;
    }

    @java.lang.SuppressWarnings("all")
    public void setPurchaseOrders(final List<PurchaseOrder> purchaseOrders) {
        this.purchaseOrders = purchaseOrders;
    }

    @java.lang.SuppressWarnings("all")
    public Supplier() {
    }

    @java.lang.SuppressWarnings("all")
    public Supplier(final Long id, final String name, final String contact, final String email, final List<Medicine> medicines, final List<PurchaseOrder> purchaseOrders) {
        this.id = id;
        this.name = name;
        this.contact = contact;
        this.email = email;
        this.medicines = medicines;
        this.purchaseOrders = purchaseOrders;
    }
}
