package com.medistock.common.exception;

public enum ErrorResponseCode {
    RESOURCE_NOT_FOUND,
    MEDICINE_NOT_FOUND,
    SUPPLIER_NOT_FOUND,
    CUSTOMER_NOT_FOUND,
    PURCHASE_ORDER_NOT_FOUND,
    SALE_NOT_FOUND,
    INSUFFICIENT_STOCK,
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    DUPLICATE_RESOURCE,
    INVALID_STATE_TRANSITION,
    METHOD_NOT_ALLOWED,
    INTERNAL_SERVER_ERROR
}
